### ISSUE TITLE
Any benchmark results could be shared?

### ISSUE THREAD

**Issue by xychu** [guillaume-be/rust-bert#114]
Great project and I know `/benches` are there, but from https://github.com/guillaume-be/rust-bert/issues/98, I think it would be better to list some benchmark results to show rust-bert's performance.

**Comment by guillaume-be** [comment]
Hello @xychu ,

Yes, following the questions regarding performance of this implementation, especially with respect to the Python version, I have documented a number of benchmarks.

The most recent of them can be found at https://guillaume-be.github.io/2020-11-21/generation_benchmarks, where speed-ups on the order of 60% to 100% could be observed for translation and summarization. For more complex generation pipelines (including sampling), benefits can be significantly higher, with speed-ups close to 500%.

Limited performance gains can be expected for simpler pipelines (classification, question answering...) since this library shares the tensor operations backend with Pytorch. A more comprehensive set of benchmarks (covering these non-text generation pipelines) can be found in the following [paper](https://www.aclweb.org/anthology/2020.nlposs-1.4.pdf).

I will add these references to the library README, thank you for the suggestion.
