### ISSUE TITLE
Refactor Translation Languages Setup

### ISSUE THREAD

**Issue by sno2** [guillaume-be/rust-bert#118]
Would it be better if we had an enum called `Language` that held traits named `English, French, German...`?  In the translation function, we could then define a tuple struct that looks like the following: `(Language, Language)`.  The first element in the tuple would be the language that is given with the second element being the language that it would be translated to.  We could then do a match on the tuple to get all of the correct translations and provide the implementation  within the body of each of the match statements.  The catching statement would probably panic.  This would make it a lot easier for people to use the library as an API as they could just serialize the `Language` traits with a string and pass them into the translate function as a tuple.  However, readability would suffer so we would need to make sure we have docs on this.  I figured I might as well post this here to get some input as I can't work on this today.

**Comment by guillaume-be** [comment]
Hello @sno2 ,

Thank you for the suggestion. I would like to better understand the drawbacks of the current approach and the proposed alternative. My understanding is that you would like to replace the current Language Enum defined at https://github.com/guillaume-be/rust-bert/blob/d4113bf7cfbc0044d9f283d4d6d5650d4c43e6d5/src/pipelines/translation.rs#L71 (containing actually a translation model setting from source to target) to a single language (e.g. replace `FrenchToEnglish` by `French` and `English`). The `TranslationConfig` defined at https://github.com/guillaume-be/rust-bert/blob/d4113bf7cfbc0044d9f283d4d6d5650d4c43e6d5/src/pipelines/translation.rs#L310 would then take 2 languages as an input instead of a single language, and perform the validation to see if the language pair is supported.

This would replace:
```rust
pub fn new(language: Language, device: Device) -> TranslationConfig {
    let translation_resource = match language {
        Language::EnglishToFrench => RemoteTranslationResources::ENGLISH2FRENCH,
        Language::EnglishToSpanish => RemoteTranslationResources::ENGLISH2SPANISH,
         ...
     }
    TranslationConfig { }
}
```
By:
```rust
pub fn new(source_language: Language, target_language: Language, device: Device) -> TranslationConfig {
    let translation_resource = match (source_language, target_language) {
        (Language::English, Language::French) => RemoteTranslationResources::ENGLISH2FRENCH,
        (Language::English, Language::Spanish)  => RemoteTranslationResources::ENGLISH2SPANISH,
         ...
       _ -> Err(
                  RustBertError::InvalidConfigurationError(
                      format!("Translation not implemented for {} to {}", 
                                   source_language, target_language)
                  )
              )
     }
    TranslationConfig { }
}
```

In general this is feasible but I do not really understand how this would impact the possibility to serialize a configuration. The API gets possibly better to use in case we do have a huge number of support translation models. The drawback is that there is a significant possibility to create a configuration that is invalid, while the current setup ensures support for all language pairs provided in the Enum.

As this would be a top-level API breaking change, I want to make sure the benefits far outweigh the drawback and break of the backward compatibility.

Note that the language information should be passed at the configuration step rather than the translate step, as a model supports a single language pair when created (the set of weights (~500MB) is specific to a specific language pair).

**Comment by guillaume-be** [comment]
@sno2 ,
I wanted to let you know that the feature you suggested will be implemented as part of https://github.com/guillaume-be/rust-bert/pull/175. Thank you for the refactoring suggestion - I am happy to hear your feedback if you have some on the new implementation.
