### ISSUE TITLE
Chinese <-> English Translation Model

### ISSUE THREAD

**Issue by edwin0cheng** [guillaume-be/rust-bert#130]
Hi, I would hope rust-bert supports zh<->en translation. 

And in huggingface db : 
https://huggingface.co/Helsinki-NLP/opus-mt-zh-en

So I think it is possbile right ? If that sounds right, I'll try making a PR.

**Comment by guillaume-be** [comment]
Hello @edwin0cheng ,

I have implemented a number of additional translation models last week, which I am hoping to merge early next week (see https://github.com/guillaume-be/rust-bert/tree/additiona_translation_models). This includes `zh <-> en`. This model offers a high number of prefixes for several languages. I will add you as a reviewer to the PR when I open it so that you can have a look at the language codes and translation generated. 

So far I have added Mandarin and Cantonese - maybe additional prefixes would be useful.

**Comment by edwin0cheng** [comment]
Great ! Thanks a lot !
