### ISSUE TITLE
Passing GenerateOptions, or similar, into summarization models?

### ISSUE THREAD

**Issue by kingpalethe** [guillaume-be/rust-bert#211]
Background:

In recent releases, it is possible to pass in additional arguments, "at runtime" into generation models, by providing `GenerateOptions`, as shown in the code sample here: https://github.com/guillaume-be/rust-bert/issues/200#issuecomment-974611617 -- the relevant function, which takes these `GenerationOptions`, is `generate`, shown here: https://github.com/guillaume-be/rust-bert/blob/4175942cc458f10ad351f8b033437845f2861861/src/pipelines/generation_utils.rs#L1578

Please excuse me if this should be obvious:

We are also looking to pass in "options" like this, at runtime, for summarization models, such as Pegasus -- for example, specifying a value for  `num_beams`. 

My best guess is that this function might need to be modified or extended to allow for this: https://github.com/guillaume-be/rust-bert/blob/55577eb09c2a0039272ca471a608be7a6136635d/src/pipelines/summarization.rs#L257

Is that possible or is there a suggested workaround?

thanks much

**Comment by guillaume-be** [comment]
Hello @kingpalethe ,

The summarization model is a high-level wrapper providing a set of sensible defaults (model, number of beams and minimum and maximum length). It otherwise only calls the `generate` method of the `LanguageModel` trait:

```rust
    pub fn summarize<S>(&self, texts: &[S]) -> Vec<String>
    where
        S: AsRef<str> + Sync,
    {
        match &self.prefix {
            None => self.model.generate(Some(texts)),
            Some(prefix) => {
                let texts = texts
                    .iter()
                    .map(|text| format!("{}{}", prefix, text.as_ref()))
                    .collect::<Vec<String>>();
                self.model.generate(Some(&texts))
            }
        }
    }
```

You can already create an instance of the correct pre-trained summarization model and call `generate` with your choices of options on it without using the `Summarization` pipeline. The summarization capabilities are fully implemented in the model weights you are loading and settings such as min/max length - there is no additional code logic that is specific to summarization.

**Comment by kingpalethe** [comment]
Thanks!
