### ISSUE TITLE
Model creation panics in async runtime

### ISSUE THREAD

**Issue by FlixCoder** [guillaume-be/rust-bert#213]
When I do a mere `SentimentModel::new(Default::default())?` in a `tokio::main` function, the application crashed:

```
The application panicked (crashed).
Message:  Cannot drop a runtime in a context where blocking is not allowed. This happens when a runtime is dropped from within an asynchronous context.
```

**Comment by mfelsche** [comment]
I can confirm this issue and have experienced it with tokio. The reason for this is the usage of the `cached_path` crate which uses `reqwest` with the `blocking` feature. This feature leads to those crashes. I think this is the exact place: https://github.com/seanmonstar/reqwest/blob/v0.11.8/src/blocking/wait.rs#L69

**Comment by guillaume-be** [comment]
Hello @FlixCoder , @mfelsche ,

Thank you for raising this. You are right that the library currently relies on `cached_path` which uses a blocking API on `tokio` to download the resource files. Generally, the `rust-bert` library offers a synchronous API and there are no plans for offering asynchronous methods. A model would typically be spawned synchronously and can receive asynchronous requests as illustrated in https://github.com/epwalsh/rust-dl-webserver/blob/master/src/main.rs.

It is possible to create an instance of the `SentimentModel` by using the `spawn_blocking` method in a tokio async method:

```rust
use rust_bert::pipelines::sentiment::SentimentModel;
use std::error::Error;
use tokio;

#[tokio::main]
pub async fn main() -> Result<(), Box<dyn Error>> {
    let blocking_task =
        tokio::task::spawn_blocking(|| SentimentModel::new(Default::default()).unwrap());
    let sentiment_model = blocking_task.await.unwrap();
    println!("{:?}", sentiment_model.predict(&["This is great!"]));
    Ok(())
}
```

That being said, I agree that it is unfortunate to have to explicitely call the tokio blocking API to create an instance of such model only because of the download helpers in the library. It may be beneficial to rely on lightweight download crates to do the same, such as `ureq`: https://github.com/algesten/ureq. 

@epwalsh I would be interested to hear your thoughts on that and if this may make the integration of `cached-path` and `rust-bert` easier in tokio runtimes.

**Comment by FlixCoder** [comment]
Thank you! I would appreciate seeing this in the documentation if possible. :)

Or checking whether there is a runtime running and doing spawn_blocking inside or failing on it, although that is probably not possible without importing tokio, which wouldn't be great just for this.

**Comment by guillaume-be** [comment]
Documentation and example added with https://github.com/guillaume-be/rust-bert/pull/217
