### ISSUE TITLE
Question - GPT2 how to obtain score per token

### ISSUE THREAD

**Issue by avnerbarr** [guillaume-be/rust-bert#224]
Hello,

Is it possible to get the score per generated token rather than the overall score?
If not, how would you go about extracting that information or which code specifically would need to be modified? Any pointers would be highly appreciated !

**Comment by guillaume-be** [comment]
Hello @avnerbarr ,

Apologies for the delayed response. This was so far not implemented and required a few updates to the generation code. I am pushing a pull request that would implement this feature. Note that the individual token scores will only be available if you use the `generate_indices` method (meaning you will need to use the tokenizer to decode as a post-processing step) - as otherwise there would be no way to map the scores to individual tokens generated.

Examples for both greedy and beam-search are available in the updated GPT2 tests in the open PR: https://github.com/guillaume-be/rust-bert/pull/238
