### ISSUE TITLE
`Utf8Error` when generating language using GPT2Generator

### ISSUE THREAD

**Issue by johannesvollmer** [guillaume-be/rust-bert#27]
Very rarely, the process panics when generating language with the GPT2Generator. I've seen this error multiple times now, they are all similar to this one:

`FromUtf8Error { bytes: [118, 97, 110, 105, 108, 108, 97, 32, 102, 108, 97, 118, 111, 114, 101, 100, 32, 105, 99, 101, 32, 99, 114, 101, 97, 109, 10, 10, 49, 32, 49, 226, 129], error: Utf8Error { valid_up_to: 31, error_len: None }`.

I can upload the exact code that I use, but as I use sampling, this will not always produce the error. 

Here's the backtrace where the error occured (excerpt):
```
  13: core::result::Result<alloc::string::String, alloc::string::FromUtf8Error>::unwrap<alloc::string::String,alloc::string::FromUtf8Error>
             at /rustc/5e1a799842ba6ed4a57e91f7ab9435947482f7d8\src\libcore\result.rs:956
  14: rust_tokenizers::preprocessing::tokenizer::gpt2_tokenizer::{{impl}}::convert_tokens_to_string
             at C:\Users\Johannes\.cargo\registry\src\github.com-1ecc6299db9ec823\rust_tokenizers-2.0.4\src\preprocessing\tokenizer\gpt2_tokenizer.rs:120
  15: rust_tokenizers::preprocessing::tokenizer::base_tokenizer::Tokenizer::decode<rust_tokenizers::preprocessing::tokenizer::gpt2_tokenizer::Gpt2Tokenizer,rust_tokenizers::preprocessing::vocab::gpt2_vocab::Gpt2Vocab>
             at C:\Users\Johannes\.cargo\registry\src\github.com-1ecc6299db9ec823\rust_tokenizers-2.0.4\src\preprocessing\tokenizer\base_tokenizer.rs:109
  16: rust_bert::pipelines::generation::LanguageGenerator::generate<rust_bert::pipelines::generation::GPT2Generator,rust_bert::gpt2::gpt2::GPT2LMHeadModel,rust_tokenizers::preprocessing::vocab::gpt2_vocab::Gpt2Vocab,rust_tokenizers::preprocessing::tokenizer::gp
             at C:\Users\Johannes\.cargo\registry\src\github.com-1ecc6299db9ec823\rust-bert-0.7.0\src\pipelines\generation.rs:1231
  17: phrase_set_variations::main
             at .\src\main.rs:67
```

**Comment by johannesvollmer** [comment]
[Documentation](https://doc.rust-lang.org/std/str/struct.Utf8Error.html):
`error_len(&self) -> Option<usize>`: Provides more information about the failure:

`None`: __the end of the input was reached unexpectedly. If a byte stream (such as a file or a network socket) is being decoded incrementally, this could be a valid char whose UTF-8 byte sequence is spanning multiple chunks.__

**Comment by guillaume-be** [comment]
Hello,

Thank you very much fro raising this issue and for the detailed error backtrace. The issue is caused by the tokenizer decoding process. The GPT2 tokenizer relies on utf-8 bytes to encode/decode unicode strings in order to limit the size of the vocabulary. 

In rare cases the GPT2 model may output a sequence of bytes that the tokenizer cannot decode as they are invalid UTF-8 sequences. the example provided above: `[118, 97, 110, 105, 108, 108, 97, 32, 102, 108, 97, 118, 111, 114, 101, 100, 32, 105, 99, 101, 32, 99, 114, 101, 97, 109, 10, 10, 49, 32, 49, 226, 129]` is indeed invalid.

The Python Transformers library relies on a graceful handling on the invalid byte sequences by default, and replaces the invalid byte sequences by the unknown character: �. With your example:

```python
from transformers import GPT2Tokenizer
tokenizer = GPT2Tokenizer.from_pretrained('gpt2')
tokenizer.decode([118, 97, 110,105, 108, 108, 97, 32, 102, 108, 97, 118,111, 114, 101, 100, 32, 105, 99, 101, 32, 99, 114, 101, 97, 109, 10, 10, 49, 32, 49, 226, 129])
```
outputs:
`'�������A��������A���A�����++RAR��'`

The default mechanism used in the Rust crate was a strict utf-8 decoding, causing the problem to panic when the model generates an invalid sequences. As this is most likely not the desired default behaviour, I have updated the tokenization library and I am pushing an updated version of this crate using these new tokenizers.

It should be published in the next hour. You can already update to the new tokenization mechanism by running a fresh compilation.

Thanks again for catching this.

**Comment by johannesvollmer** [comment]
Oh wow, this was really quick, haha, thanks! <3

What exactly does happen if there is an invalid byte sequence produced by the model? Will it just be excluded from the returned List of Strings?

**Comment by guillaume-be** [comment]
The current behaviour will be to replace the incorrect token sequences by `�`, aligned with the original Transformers library. For generation you could inspect the output for such symbols that would indicate invalid UTF-8 generated, and ignore/re-run the generation sequence (as this should occur very rarely)

**Comment by johannesvollmer** [comment]
That's cool. Keep up the good work!
