### ISSUE TITLE
[FEATURE] GPT-J support

### ISSUE THREAD

**Issue by lerouxrgd** [guillaume-be/rust-bert#285]
Hello,

How hard would it be to add [GPT-J](https://huggingface.co/docs/transformers/model_doc/gptj) support ?

At a first glance it looks pretty similar to GPT-2, does copying its code and adapt specific layers be a good starting point ?

It looks quite memory intensive so the float16 version seems more usable in practice, would supporting float16 out-of-the-box be difficult ?

**Comment by guillaume-be** [comment]
Hello @lerouxrgd ,

Yes - the architecture of GPT-J should be straightforward to adapt from either gpt-neo or gpt2. The model size is indeed challenging for development and integration testing. It is currently possible to convert a model loaded in memory to half precision using `VarStore::half`: https://github.com/LaurentMazare/tch-rs/blob/f08eeb4f9ca5efd2ece00caec87bfec912cd0a40/src/nn/var_store.rs#L402

Unfortunately this does not help because the size of the models would probably require loading directly the model as `fp16`, which as far as I know is not yet possible using `tch-rs`. It may make sense to investigate if this would be an option before starting work on GPT-J (unfortunately I could not find relevant models for GPT-J with a smaller size).

**Comment by lerouxrgd** [comment]
Hello @guillaume-be ,

I have a basic implementation of the architecture but I struggle to convert/load [gpt-j-6b](https://huggingface.co/EleutherAI/gpt-j-6B/tree/main).

So far I have tried to use `convert_model.py` as is (which seems to force float32 type by using `np.ascontiguousarray(v.cpu().numpy().astype(np.float32))`),
and I have also tried to modify it by using simply `np.ascontiguousarray(v.cpu().numpy())`.
In both cases when I try to load the model on the CPU, I get the error:

Error: Tch tensor error: Internal torch error: Unrecognized data format
Exception raised from load at ../torch/csrc/jit/serialization/import.cpp:449 
// and much more cpp related stuff

Are there special settings to use to convert a GPT-based model ? Do you have any clue about what might be the issue ?

PS: I am using a server with about 88 Gb of RAM, so I guess the model in float32 should be loadable on the CPU.

**Comment by lerouxrgd** [comment]
Actually it was just a wrong path to the local model, I am able to load it. Although I now have to debug the forward calculations.

**Comment by lerouxrgd** [comment]
Hello @guillaume-be ,

I've finally managed to run [gpt-j-6b](https://huggingface.co/EleutherAI/gpt-j-6B/tree/main) on both CPU (using it as-is with float32) and GPU (using float16). For using the model in float16 on the GPU I have to first load it on the CPU (and convert each layer's weights to float16 just after loading it), and then migrate the whole `var_store` to the GPU (using `VarStore::set_device`).

I tried to test it with the following input:

```rs
let input_context_1 = "It was a very nice and sunny";
let input_context_2 = "It was a gloom winter night, and";
let output = model.generate(&[input_context_1, input_context_2], None);
```
Sadly the result is pretty much garbage:
- Using float32 on the CPU:
  1. "It was a very nice and sunny Scriptkiller Thin flatî cookiebers suckSmithitentagle Zeit ping pgensitivity Hok suck AU Scot Scot Osw ligqualqq"
  2. "It was a gloom winter night, andTruth dueDue Babel EB Catalog usable parentheses Kavanaugh wel nin HindREG superf Tar Carn Kitt CONFIGWINDOWSmult Maur anecdINSJesus"
- Using float16 on the GPU:
  1. "It was a very nice and sunny Scriptkiller Thin flatî cookiebers suckSmithitentagle Zeit ping pgensitivity Hok suck AU Scot Scot Osw ligqualqq"
  2. "It was a gloom winter night, and ExxonWOR lover speeding 386 Identity neut cap cap cap\u{a0}\u{a0}\u{a0}reat decide Identity Babel Denver Identity Identity Identity Identity TI treacher Chilicession"
  
The results are deterministic though, so I get the same outputs every time. Do you have an idea of what could be the issue ?
If you want to have a look at the code, it's on [this branch](https://github.com/lerouxrgd/rust-bert/tree/gpt-j).

**Comment by guillaume-be** [comment]
Hello @lerouxrgd ,

When debugging language models I usually follow these steps:
1) Ensure you have a Python version of the code running with access to a debugger to be able to compare the input at different stages of the pipeline. This is critical as otherwise it may be very difficult to identify the source of the mismatch. Ensure that the generation settings are identical for both the Python and Rust example.
2) Inspect he output of the tokenization. While GPT-J uses GPT2 as a tokenizer, it seems there is some configuration files stored on the model hub (`tokenizer_configuration`, `special_token_map`, ...) and this may impact the behaviour of the tokenizer. Compare the input at the indices level before they are passed to the model for generation.
3) Pass a single set of input ids to the model (without generation) and compare the output of the Python version to Rust. If the last hidden states of the model differ, walk your way backwards through the layer to identify when they start being different (e.g. after embeddings stage / after self attention stage / after dense layer, after layer norm...)
4) If the inputs are all identical, the issue may come from the way the past states are handled. Check the output of the generate pipeline right after the first token generation, and then through the generation stages up to the input for the second token. You may want to work without beam search to simplify the debugging.

I also noted that a "tiny" version of GPT-J is available (https://huggingface.co/anton-l/gpt-j-tiny-random) which you may consider for step 3, and for implementing the tests in the library when merging the feature.

**Comment by lerouxrgd** [comment]
Thank you for tips, I'll give it a try !

**Comment by lerouxrgd** [comment]
Hello @guillaume-be ,
After long debugging sessions I realized that I had just forgot to include the "lm_head" layer, now I have the same results in Rust and Python !
