### ISSUE TITLE
failed to build the example

### ISSUE THREAD

**Issue by MaYuandong** [guillaume-be/rust-bert#312]
error occurred: Command "c++" "-O0" "-ffunction-sections" "-fdata-sections" "-fPIC" "-gdwarf-4" "-fno-omit-frame-pointer" "-m64" "-I" "/opt/libtorch/include" "-I" "/opt/libtorch/include/torch/csrc/api/include" "-Wl,-rpath=/opt/libtorch/lib" "-std=c++14" "-D_GLIBCXX_USE_CXX11_ABI=1" "-o" "/home/john/Projects/conversation/target/debug/build/torch-sys-b3197540abc4eebd/out/libtch/torch_api.o" "-c" "libtch/torch_api.cpp" with args "c++" did not execute successfully (status code exit status: 1).

**Comment by guillaume-be** [comment]
Hello @MaYuandong ,

Could you please share more information on the library version you are using (from crates.io or from the repository) and the version of Libtorch you are using?

**Comment by MaYuandong** [comment]
It's git clone from here, I managed to build the examples by 'cargo test', but failed to build the the conversation after copy the .rs file to a hello world project.

**Comment by zurgl** [comment]
@MaYuandong Hi, I've faced the same issue, find below the reason and the workaround.

#### Reason
The version available on [crates.io](https://crates.io/crates/rust-bert) haven't been updated since 5 Month ago, even if the version looks the same there are not the same anymore. 

#### Workaround
To make it work again use git url in place of version in your `Cargo.toml`

```toml

[dependencies]
rust-bert = { git = "https://github.com/guillaume-be/rust-bert" }
```


Hope it helps

**Comment by guillaume-be** [comment]
Indeed - I expect to publish a new release in the next few weeks, pending a few key pull requests to be merged (GPT-J implementation). This should resolve such issues.

**Comment by guillaume-be** [comment]
Closing this since a new version was release, please feel free to re-open if needed
