### ISSUE TITLE
Error with resources

### ISSUE THREAD

**Issue by sbeckeriv** [guillaume-be/rust-bert#50]
Dearest Maintainer,

I hope all is well. I like the Summarization model, however, sometimes I would get text like "Please email us at jennifer.somebody@real.email." I thought I would try out BART vs BART_CNN. I copied the config from default and removed the CNN. I loaded this in to the file in the example folder.

https://gist.github.com/sbeckeriv/db5711f86be38df6bb23ab34e803afd4

Running this gives this error:
```
Error: ErrorMessage { msg: "cannot find model.encoder.layers.4.fc1.bias in \"/home/becker/.cache/.rustbert/bart/model.ot\"" }
```

any suggestions on how i can load the BART data vs BART_CNN would help appreciated.

Thanks again,
Becker

**Comment by guillaume-be** [comment]
Hello @sbeckeriv 

While the BART model has all the weights required to run summarization, it was not finetuned for a summarization task and cannot be used in a `BartForConditionalGeneration` module. You can actually try to force loading them by removing the `/ "model"` at https://github.com/guillaume-be/rust-bert/blob/a459fa1b1734f04c3a3af71c29c23b4f7afd03e8/src/bart/bart.rs#L365
The results will however not make any sense since this model was not trained for the task.

In order to offer more variety, I have uploaded and registered another BART-based summarization model. This was trained on the [XSum dataset](https://github.com/EdinburghNLP/XSum), and can be used as a BART_XSUM resource. I would recommend trying this one if you would like to compare two summarization models.

This model is available as a result of https://github.com/guillaume-be/rust-bert/pull/51

**Comment by sbeckeriv** [comment]
Hello @guillaume-be 

You are amazing. I can not thank you enough for you help. I look forward to trying this new resource. 

Becker

**Comment by sbeckeriv** [comment]
Hello @guillaume-be,

I tried XSum datasets and the results were comical. Unfortunately I cant use them. Thanks! it was good to compare. 

Becker
